// Perguntas originais de reflexão. Inspiradas em campos teóricos, não são citações de autores.
export const prompts = {
  "Autoestima": [
    "Qual qualidade sua você costuma minimizar?",
    "Em que momentos você sente que precisa provar seu valor?",
    "O que mudaria se sua dignidade não dependesse do desempenho?",
    "Que crítica interna aparece quando você erra?",
    "Como você reconhece uma conquista sem diminuí-la?",
    "Que expectativa de outras pessoas você tomou como sua?",
    "Como você pode se tratar com mais respeito hoje?",
    "O que você admira em sua própria trajetória?",
    "Que comparação tem enfraquecido sua confiança?",
    "O que significa valorizar-se sem precisar ser perfeito?",
    "Quando você se sentiu genuinamente capaz?",
    "Que evidências apoiam uma visão mais equilibrada sobre você?"
  ],
  "Autoconhecimento": [
    "Que situação recente revelou uma necessidade importante sua?",
    "Qual emoção você tenta explicar antes de senti-la?",
    "Que escolha sua expressou um valor pessoal?",
    "Qual hábito você mantém sem saber por quê?",
    "Em que ambientes você consegue ser mais espontâneo?",
    "O que costuma desencadear suas reações automáticas?",
    "Que parte da sua história você interpreta de forma diferente hoje?",
    "Como você distingue desejo próprio de expectativa externa?",
    "Qual limite seu você conheceu recentemente?",
    "Que crença antiga talvez mereça revisão?",
    "Quais necessidades você tem dificuldade de comunicar?",
    "Qual pergunta sobre si você ainda não se permitiu fazer?"
  ],
  "Resiliência": [
    "Que recurso ajudou você em outra fase difícil?",
    "O que está sob seu controle nesta situação?",
    "O que pode ser aceito sem ser aprovado?",
    "Que apoio seria útil pedir agora?",
    "Como medir progresso sem exigir que tudo esteja resolvido?",
    "O que essa experiência revela sobre seus limites?",
    "Qual próximo passo é viável, ainda que pequeno?",
    "Que narrativa sobre fracasso precisa ser examinada?",
    "Você está se recuperando ou apenas se cobrando resistência?",
    "Qual pausa permitiria agir com mais clareza?",
    "O que merece ser preservado enquanto você muda?",
    "Que capacidade desenvolvida você pode reconhecer?"
  ],
  "Relacionamentos": [
    "Que limite precisa ser comunicado com clareza?",
    "Como você percebe quando não está sendo ouvido?",
    "Qual pedido você evita fazer por medo da resposta?",
    "O que diferencia cuidado de controle nesta relação?",
    "Que acordo seria justo para ambas as partes?",
    "Quais atitudes fortalecem confiança na prática?",
    "Que papel você costuma assumir em conflitos?",
    "Como discordar sem desrespeitar?",
    "O que você precisa compreender antes de reagir?",
    "Existe reciprocidade entre suas entregas e necessidades?",
    "Como reparar uma conversa difícil com responsabilidade?",
    "Qual relação permite que você seja autêntico?"
  ],
  "Luto e perdas": [
    "De que maneira essa perda modificou sua rotina?",
    "Qual lembrança você gostaria de preservar?",
    "Que sentimentos diferentes coexistem hoje?",
    "Que tipo de companhia seria acolhedora neste momento?",
    "O que tem sido mais difícil explicar aos outros?",
    "Qual ritual pode ajudar a honrar essa história?",
    "Como você percebe suas necessidades nos dias mais intensos?",
    "Que cobrança sobre o tempo de sofrer pode ser flexibilizada?",
    "O que permanece significativo apesar da ausência?",
    "Como respeitar seus limites em datas marcantes?",
    "Que forma de apoio você consegue aceitar?",
    "Que espaço existe para saudade e continuidade ao mesmo tempo?"
  ],
  "Autocompaixão": [
    "Como você falaria com uma pessoa querida na mesma situação?",
    "Que frase de autocrítica pode ser reformulada com cuidado?",
    "Qual sofrimento você tem tratado como falha pessoal?",
    "O que você precisa reconhecer sem se julgar?",
    "Como lembrar que dificuldades fazem parte da experiência humana?",
    "Que gesto simples expressaria gentileza consigo?",
    "Você consegue observar a emoção sem se definir por ela?",
    "Como acolher um erro e ainda assumir responsabilidade?",
    "Que expectativa rígida impede você de descansar?",
    "O que significa oferecer compreensão sem desistir de crescer?",
    "Como distinguir autocuidado de fuga?",
    "Qual necessidade legítima pede atenção agora?"
  ],
  "Pensamentos e crenças": [
    "Qual pensamento automático surgiu antes da emoção?",
    "Que fatos confirmam ou questionam sua interpretação?",
    "Há outra explicação plausível para o ocorrido?",
    "Você está tratando uma possibilidade como certeza?",
    "Que conselho daria a alguém diante dos mesmos fatos?",
    "Que palavras absolutas aparecem na sua fala interna?",
    "Como distinguir fato, hipótese e receio?",
    "Qual custo de acreditar nessa ideia sem examiná-la?",
    "O que mudou quando você verificou uma suposição?",
    "Que pensamento alternativo seria mais realista, não apenas otimista?",
    "Você está prevendo o futuro a partir de uma única experiência?",
    "Qual pequena experiência poderia testar essa crença?"
  ],
  "Propósito e valores": [
    "O que dá sentido a um dia comum?",
    "Que valor seu merece mais espaço na rotina?",
    "O que você faria por convicção, não por reconhecimento?",
    "Em que situação você escolheu agir conforme seus princípios?",
    "Qual contribuição você deseja oferecer ao seu entorno?",
    "Que tarefa cotidiana expressa algo importante para você?",
    "Como a adversidade afeta sua percepção de sentido?",
    "Que vínculo ou experiência desperta gratidão genuína?",
    "O que você quer construir sem depender de resultados imediatos?",
    "Quais decisões se afastaram dos seus valores?",
    "Como diferenciar propósito de pressão por produtividade?",
    "Que escolha pequena aproxima sua vida do que importa?"
  ],
  "Emoções e regulação": [
    "Onde você percebe essa emoção no corpo?",
    "Que nome mais preciso descreveria o que você sente?",
    "O que aconteceu imediatamente antes dessa reação?",
    "Qual necessidade sua pode estar ligada a esse sentimento?",
    "Como você pode dar espaço à emoção sem agir impulsivamente?",
    "Que estratégia já ajudou você a se reorganizar?",
    "Em que situações o silêncio ajuda ou atrapalha?",
    "Que sinal indica que você precisa de uma pausa?",
    "O que muda quando você descreve a emoção sem julgá-la?",
    "Qual reação automática você gostaria de compreender melhor?",
    "Como reconhecer duas emoções contraditórias ao mesmo tempo?",
    "Que cuidado concreto pode apoiar você neste momento?"
  ],
  "Limites e assertividade": [
    "O que você aceita por receio de decepcionar?",
    "Qual pedido exige uma resposta mais clara?",
    "Como dizer não sem justificar excessivamente?",
    "Qual responsabilidade não é sua?",
    "Onde você confunde disponibilidade com obrigação?",
    "Que consequência pode precisar ser negociada?",
    "Como comunicar uma necessidade sem acusar?",
    "Que limite protege um valor importante?",
    "O que acontece quando você ignora seu próprio cansaço?",
    "Que conversa merece ser preparada com antecedência?",
    "Como reconhecer o limite do outro sem abandonar o seu?",
    "Qual acordo pode tornar a relação mais previsível?"
  ],
  "Mudança e hábitos": [
    "Qual comportamento você deseja compreender antes de mudar?",
    "Que situação costuma iniciar esse hábito?",
    "Que recompensa mantém esse padrão?",
    "Qual mudança seria pequena o suficiente para começar?",
    "Que ambiente facilitaria a ação desejada?",
    "Como reconhecer recaídas sem concluir que nada funciona?",
    "Que apoio tornaria a nova rotina sustentável?",
    "Você definiu uma ação observável ou apenas uma intenção?",
    "Qual obstáculo pode ser antecipado?",
    "Como medir consistência sem perfeccionismo?",
    "Que hábito deixou de servir à pessoa que você é hoje?",
    "O que ajudaria a retomar o caminho após uma interrupção?"
  ],
  "Gratidão e recursos": [
    "Que gesto cotidiano trouxe alívio recentemente?",
    "Qual pessoa contribuiu para sua trajetória?",
    "Que recurso você possui e tende a esquecer?",
    "Que aprendizado merece reconhecimento?",
    "Como agradecer sem negar uma dificuldade real?",
    "Que pequeno momento foi significativo nesta semana?",
    "De que forma você pode expressar reconhecimento?",
    "Qual lugar desperta sensação de pertencimento?",
    "Que relação ou experiência você valoriza hoje?",
    "O que você conseguiu fazer com os recursos disponíveis?",
    "Qual suporte está presente mesmo em fases difíceis?",
    "Como cultivar apreciação sem transformar gratidão em obrigação?"
  ]
};
export const theoreticalReferences = [
{autor:"Aaron T. Beck",tema:"terapia cognitiva; pensamentos automáticos e reestruturação cognitiva",fonte:"https://dictionary.apa.org/cognitive-therapy"},
{autor:"Viktor E. Frankl",tema:"logoterapia; valores e sentido",fonte:"https://dictionary.apa.org/logotherapy"},
{autor:"Kristin Neff e Christopher Germer",tema:"autocompaixão, humanidade compartilhada e atenção plena",fonte:"https://pubmed.ncbi.nlm.nih.gov/23775511/"},
{autor:"Carl R. Rogers",tema:"escuta empática e abordagem centrada na pessoa",fonte:"Referência conceitual para estudo editorial; requer revisão bibliográfica"}
];
